Module.Catalogs.WebUI/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using KristaShop.Common.Enums;
using KristaShop.Common.Extensions;
using KristaShop.Common.Models;
using Module.Catalogs.Business.Models;
using Module.Common.Business.Models;

namespace Module.Catalogs.WebUI.Models {
    public class ProductViewModel {
        public CatalogItemGroupNew ItemFull { get; set; }
        [JsonIgnore]
        public CatalogDTO Catalog { get; set; }
        [JsonIgnore] 
        public CatalogItemDTO SelectedProduct { get; set; }
        [JsonIgnore]
        public bool IsFavorite { get; set; }

        public ProductViewModel(CatalogItemGroupNew itemFull, CatalogDTO catalog, bool excludePrices) {
            ItemFull = itemFull;
            Catalog = catalog;

            if (excludePrices) {
                ItemFull.CommonPrice = 0;
                ItemFull.CommonPriceInRub = 0;
            }


            var selectedSize = itemFull.CatalogItems.First(x => x.SizeValue.Equals(itemFull.Sizes.First()));
            SelectedProduct = selectedSize.Items.First(x => x.Color.Id == selectedSize.Colors.First().Id);
        }

        public string Serialize() {
            return JsonSerializer.Serialize(this, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });
        }
    }
}

Module.Catalogs.WebUI/Controllers/CatalogController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using KristaShop.Common.Enums;
using KristaShop.Common.Exceptions;
using KristaShop.Common.Extensions;
using KristaShop.Common.Models;
using KristaShop.Common.Models.Filters;
using KristaShop.Common.Models.Session;
using KristaShop.Common.Models.Structs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Module.Catalogs.WebUI.Models;
using Module.Common.Business.Interfaces;
using Module.Common.WebUI.Base;
using Module.Common.WebUI.Infrastructure;
using Module.Common.WebUI.Models;
using Serilog;
using Microsoft.FeatureManagement;
using Module.Catalogs.Business.Interfaces;
using Module.Catalogs.Business.Models;

namespace Module.Catalogs.WebUI.Controllers {
    [Permission]
    [Authorize(AuthenticationSchemes = GlobalConstant.Session.AllFrontSchemes)]
    public class CatalogController : AppControllerBase {
        private readonly ICatalogService _catalogService;
        private readonly ICatalogAccessService _catalogAccessService;
        private readonly IMapper _mapper;
        private readonly ICategoryService _categoryService;
        private readonly ICatalogItemsService _catalogItemsService;
        private readonly IFavorite1CService _favorite1CService;
        private readonly ILogger _logger;
        private readonly ISettingsManager _settingsManager;
        private readonly IFeatureManager _featureManager;

        public CatalogController(ICategoryService categoryService, ICatalogItemsService catalogItemsService,
            ICatalogService catalogService, ICatalogAccessService catalogAccessService,
            IMapper mapper, ILogger logger, IFavorite1CService favorite1CService, ISettingsManager settingsManager,
            IFeatureManager featureManager) {
            _categoryService = categoryService;
            _catalogItemsService = catalogItemsService;
            _catalogService = catalogService;
            _catalogAccessService = catalogAccessService;
            _favorite1CService = favorite1CService;
            _mapper = mapper;
            _logger = logger;
            _settingsManager = settingsManager;
            _featureManager = featureManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(NomFilterDTO filter, int page = 1, bool? showRegistrationForm = null) {
            try {
                ViewBag.ShowRegistartionFrom = showRegistrationForm != null && UserSession is UnauthorizedSession;
                
                CatalogDTO currentCatalog = null;
                if (string.IsNullOrEmpty(filter.CatalogUri) && filter.CatalogId == CatalogType.All) {
                    currentCatalog = await _catalogAccessService.GetFirstAvailableCatalogAsync(UserSession);
                } else {
                    currentCatalog = await _catalogAccessService.GetCatalogByIdOrUriIfAvailableAsync(UserSession,
                        filter.CatalogUri, filter.CatalogId);
                }

                if (currentCatalog.Id == CatalogType.Preorder &&
                    !_settingsManager.Settings.PreorderParts.IsEmpty()) {
                    return await _groupedCatalogItemsIndex(currentCatalog, filter, page);
                }

                var result = await _getCatalogItemsAsync(currentCatalog, filter,
                    _settingsManager.Settings.FrontCatalogOnPageCount, page);
                return View(result);
            } catch(EntityNotFoundException ex) {
                if (UserSession is UnauthorizedSession)
                    return RedirectToAction("Index", "Home", new { id = "showloginform" });
                SetNotification(OperationResult.Failure("Вам не доступен данный каталог"));
                return RedirectToAction("Index", "Home");
            }
            catch(CatalogAccessException ex) {
                SetNotification(OperationResult.Failure("Вам не доступен данный каталог"));
                return RedirectToAction("Index", "Home");
            } catch (Exception ex) {
                _logger.Fatal(ex, "Failed to display catalog models. {message}. Filter: {@filter}; Page: {page}; User: {@user}",
                    ex.Message, filter, page, UserSession);
                return RedirectToAction("Common500", "Error");
            }
        }

        private async Task<NomFilterViewModel> _getCatalogItemsAsync(CatalogDTO catalog, NomFilterDTO filter, int modelsPerPage, int page = 1) {
            filter.SetDataFromCatalog(catalog);
            var productsFilter = _mapper.Map<ProductsFilterExtended>(filter);
            productsFilter.HideEmptySlots = !catalog.IsOpen;

            var currentPage = Page.Create(page - 1, modelsPerPage);
            var models = await _catalogItemsService.GetFullModelsAllListAsync(productsFilter, UserSession, currentPage);
            var totalItemsCount = await _catalogItemsService.GetModelsCountAsync(productsFilter, UserSession);

            var userCatalogs = await _catalogAccessService.GetAvailableUserCatalogsFullAsync(UserSession);
            
            if (!await _featureManager.IsEnabledAsync(GlobalConstant.FeatureFlags.FeatureAdvancedFunctionality)) {
                userCatalogs.RemoveAll(x => x.Id is CatalogType.RfInStockLines or CatalogType.RfInStockParts);
            }

            return new NomFilterViewModel {
                Filter = filter,
                Catalog = catalog,
                Catalogs = userCatalogs,
                Models = models.ToPagerList(currentPage, totalItemsCount),
                Page = page
            };
        }

        private async Task<IActionResult> _groupedCatalogItemsIndex(CatalogDTO currentCatalog, NomFilterDTO filter, int page = 1) {
            var result = await _getCatalogItemsAsync(currentCatalog, filter, 10000, page);
            ViewData["PreorderParts"] = _settingsManager.Settings.PreorderParts.Parts;
            return View("IndexSections", result);
        }

        public async Task<IActionResult> Search(NomFilterDTO filter) {
            try {
                var searchLookups = new SearchLookupsViewModel();
                var (colors, sizes, sizeLines) = await _catalogItemsService.GetFilterLookupListsAsync(CatalogType.All, true);
                searchLookups.Colors = colors;
                searchLookups.Sizes = sizes;
                searchLookups.SizeLines = sizeLines;
                searchLookups.Categories = await _categoryService.GetCategoriesAsync();
                var catalogs1C = (await _catalogAccessService.GetAvailableUserCatalogsAsync(UserSession ?? new UnauthorizedSession())).Select(x => x.Id.ToProductCatalog1CId()).ToList();

                var catalogs = await _catalogService.GetCatalogsAsync(catalogs1C);
                if (!await _featureManager.IsEnabledAsync(GlobalConstant.FeatureFlags.FeatureAdvancedFunctionality)) {
                    catalogs.RemoveAll(x => x.Id is CatalogType.RfInStockLines or CatalogType.RfInStockParts);
                }

                var catalogsSelectList = new SelectList(catalogs, nameof(CatalogDTO.Id), nameof(CatalogDTO.Name));
               
                return View(new SearchPanelViewModel { SearchLookups = searchLookups, NomFilter = filter, Catalogs = catalogsSelectList });
            } catch (Exception ex) {
                _logger.Fatal(ex, "Failed to get search form. {message}. User: {@user}", ex.Message, UserSession);
                return RedirectToAction("Common500", "Error");
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Products(NomFilterDTO filter, [FromServices] ISettingsManager settingsManager) {
            try { 
                if (filter.CatalogId == CatalogType.All) {
                    filter.CatalogId = User.Identity is {IsAuthenticated: false} ? CatalogType.Open : CatalogType.All;
                }
                
                var productsFilter = _mapper.Map<ProductsFilterExtended>(filter);
                productsFilter.HideEmptySlots = filter.CatalogId != (int) CatalogType.Open;

                var models = await _catalogItemsService.GetFullModelsGroupedByCatalogsAsync(productsFilter, UserSession, 0, 0);
                var catalogs = (await _catalogService.GetCatalogsAsync(models.Keys.ToList())).ToDictionary(
                        k => k.Id, v => v);

                var result = new SearchAllViewModel {
                    Filter = filter,
                    SearchProducts = models,
                    Catalogs = catalogs,
                    SearchTitle = "Поиск по всем каталогам",
                    DescriptionSettingKey = settingsManager.Settings.OpenCatalogSearchDescription
                };

                if (filter.Categories is {Count: 1}) {
                    var category = await _categoryService.GetCategoryAsync(filter.Categories.First());
                    if (category != null) {
                        result.SearchTitle = category.Name;
                        result.HasDescription = true;
                    }
                }

                return View(result);
            } catch (Exception ex) {
                _logger.Error(ex, "Full search by filter failed, filter {@filter}. For user {@user}. {message}", filter, UserSession, ex.Message);
                SetNotification(OperationResult.Failure("Произошла ошибка во время поиска"));
                return RedirectToAction(nameof(Search), new {filter});
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Product(string articul, CatalogType catalog, int page = 1) {
            try {
                if (catalog == CatalogType.All) {
                    SetNotification(OperationResult.Failure("Каталог не выбран"));
                    return RedirectToAction(nameof(Index), new {catalogId = catalog});
                }

                var currentCatalog = await _catalogService.GetCatalogDetailsAsync(catalog);

Module.Catalogs.WebUI/Views/Catalog/Products.cshtml
@using KristaShop.Common.Enums
@using KristaShop.Common.Extensions
@using Module.Common.WebUI.Infrastructure
@model Module.Catalogs.WebUI.Models.SearchAllViewModel
@{
    ViewData["Title"] = "Найденные модели";
    const int maxLength = 8;
    const int maxLineLength = 25;
}

<div class="container p-2" method="get" asp-action="Products">
    <div class="form-row align-items-center my-3">
        @if (!Model.HasDescription) {
            <div class="col-sm-12 col-lg-9 text-center text-lg-left">
                <h1 class="text-center text-md-left text-lg-left text-xl-left header-font h1 text-uppercase">@Model.SearchTitle</h1>
            </div>
            <div class="col-sm-6 col-lg-3">
                <a type="button" href="@Url.Action("Search", new {
                                           Model.Filter.Articul,
                                           Model.Filter.Categories,
                                           Model.Filter.Sizes,
                                           Model.Filter.SizeLines,
                                           Model.Filter.Colors,
                                           Model.Filter.CatalogUri,
                                           Model.Filter.CatalogId,
                                           Model.Filter.MinPrice,
                                           Model.Filter.MaxPrice
                                       })"
                   class="btn btn-basic btn-main w-100">
                    ПАРАМЕТРЫ ПОИСКА
                </a>
            </div>
        } else {
            <div class="row py-2">
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 align-self-center">
                    <h1 class="text-uppercase text-center text-md-left text-lg-left text-xl-left header-font h1">@Model.SearchTitle</h1>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="gradient-separator"></div>
                    @await Component.InvokeAsync("DynamicPageBody", new {url = Model.DescriptionSettingKey})
                </div>
            </div>
        }
    </div>
    @if (Model.SearchProducts.Keys.Any()) {
        var firstCatalogId = Model.SearchProducts.Keys.First();
        @foreach (var catalogId in Model.SearchProducts.Keys) {
             var catalog = Model.Catalogs[catalogId];
             @if (catalog.IsOpen && !string.IsNullOrEmpty(catalog.AdditionalDescription) && (!User.Identity.IsAuthenticated || User.IsGuest())) {
                  <div class="row">
                      <div class="px-2 text-center text-justify text-md-center text-lg-left">
                          <div class="two-halfs-block two-row lg-one-row">
                              <div class="left-wrapper text-main">
                                  @Html.Raw(catalog.AdditionalDescription)
                              </div>
                              <div class="right-wrapper wrapper-3">
                                  <button data-toggle="ajax-modal" data-target="#registerModal" data-target-tab="#register-tab" class="btn-lg btn-basic btn-main mb-3 mr-3">Зарегистрируйтесь и узнайте цену</button>
                              </div>
                          </div>
                      </div>
                  </div>
              }

             <div class="d-flex my-3 flex-wrap d-block bg-dark rounded-1 text-white align-items-center p-2" data-toggle="collapse" href="#collapse-@catalog.Id" role="button" aria-expanded="@Html.AddValue(catalogId == firstCatalogId, "true", "false")" aria-controls="collapsePreorder">
                 <div class="">
                     <p class="m-auto">
                         <span class="iconify icon-font-18px align-text-bottom" data-inline="false" data-icon="eva:expand-fill"></span> @catalog.Name
                     </p>
                 </div>
                 <div class="ml-auto">
                     Найдено моделей: @Model.SearchProducts[catalogId].Count
                 </div>
             </div>
             <div class="form-row row-cols-1 row-cols-md-2 row-cols-lg-3 collapse @Html.AddValue(catalogId == firstCatalogId, "show")" id="collapse-@catalog.Id">
                 @foreach (var item in Model.SearchProducts[catalogId]) {
                     <div class="col mb-2">
                         <div class="card rounded-1 border-0 h-100 left-corner-container">
                             <a asp-action="Product" asp-controller="Catalog" asp-route-articul="@item.Descriptor.Articul" asp-route-catalog="@catalogId">
                                 <div class="image-fix-height-wrapper ratio150">
                                     <picture>
                                         <source data-srcset="@item.Descriptor.MainPhoto?width=400&height=600&format=webp 576w, @item.Descriptor.MainPhoto?width=700&height=1050&format=webp 768w" type="image/webp">
                                         <img class="lazy image rounded-1" data-srcset="@item.Descriptor.MainPhoto?width=400&height=600 576w, @item.Descriptor.MainPhoto?width=700&height=1050 768w" alt="@item.Descriptor.AltText" />
                                     </picture>
                                 </div>
                             </a>
                             @if (item.Descriptor.IsLimited && item.CatalogId.ToProductCatalog1CId() == CatalogType.Preorder) {
                                 <div class="left-corner" title="Лимитированная модель">
                                     <span>Лимитировано</span>
                                 </div>
                             }
                             <div class="card-body p-2 font-weight-5">
                                 <div class="my-2">
                                     <span class="text-main-grey">Артикул: </span><span>@item.Descriptor.Articul</span>
                                 </div>
                                 <div class="my-2">
                                     <span class="text-main-grey mr-2">Серия:</span>
                                     @{
                                         var added = 0;
                                     }
                                     @foreach (var size in item.Sizes)
                                     {
                                         if (size.Contains("-"))
                                         {
                                             if (added + size.Length > maxLineLength)
                                             {
                                                 <span class="ml-1">...</span>
                                                 break;
                                             }
                                         }
                                         else
                                         {
                                             if (added + size.Length > maxLength)
                                             {
                                                 <span class="ml-1">...</span>
                                                 break;
                                             }
                                         }
                                         added += size.Length;
                                         <span class="size-swatch">@size</span>
                                     }
                                 </div>
                                 <div class="my-2">
                                     <span class="text-main-grey mr-2">Цвет:</span>
                                     @foreach (var color in item.Colors.Take(5))
                                     {
                                         var background = string.IsNullOrEmpty(color.Image) ? color.Code : $"url({color.Image})";
                                         <span class="color-swatch" style="background: @background;" data-toggle="tooltip" data-placement="top" title="@color.Name"></span>
                                     }
                                     @if (item.Colors.Count > 5)
                                     {
                                         <span class="ml-1">...</span>
                                     }
                                 </div>
                                 @if (User.Identity.IsAuthenticated && !User.IsGuest() && !catalog.IsOpen)
                                 {
                                     <div class="my-2">
                                         <span class="text-main-grey">Цена за единицу: </span><span>@item.CommonPrice.ToTwoDecimalPlaces() $ | @item.CommonPriceInRub.ToTwoDecimalPlaces() р</span>
                                     </div>
                                 }
                                 <div class="mt-3">
                                     <a class="btn btn-basic btn-main-colored" asp-controller="Catalog" asp-action="Product" asp-route-articul="@item.Descriptor.Articul" asp-route-catalog="@catalogId">
                                         Подробнее
                                     </a>
                                 </div>
                             </div>
                         </div>
                     </div>
                 }
             </div>
         }
    } else {
        <p class="text-center h3">По Вашему запросу модели отсутствуют.</p>
    }
</div>

Module.Catalogs.WebUI/Views/Catalog/Search.cshtml
@using KristaShop.Common.Enums
@using Module.Common.WebUI.Infrastructure
@model Module.Catalogs.WebUI.Models.SearchPanelViewModel

@{
    ViewData["Title"] = "Поиск по всем каталогам";
}

<form class="container p-2 main-font h4" method="get" asp-action="Products">
    <div class="form-row justify-content-center align-items-center my-3">
        <div class="col-sm-12 col-lg-9 text-center text-lg-left">
            <h1 class="header-font h2 m-0 text-black">@ViewData["Title"]</h1>
        </div>
        <div class="col-sm-6 col-lg-3">
            <button type="submit" class="btn btn-basic btn-main w-100">НАЙТИ МОДЕЛИ</button>
        </div>
    </div>
    <div class="form-row my-2">
        <div class="col-sm-12 col-lg-6">
            <select name="CatalogId" asp-items="Model.Catalogs" class="form-control light-control">
                <option value="@((int)CatalogType.All)">По всем каталогам</option>
            </select>
        </div>
        <div class="col-sm-12 col-lg-3">
            <input type="text" class="form-control light-control" placeholder="Артикул" name="Articul" value="@Model.NomFilter.Articul">
        </div>
        <div class="col-sm-12 col-lg-3">
            <div class="row">
                <div class="col-sm-12 col-lg mr-auto pr-lg-0">
                    <input type="text" class="form-control light-control" placeholder="Цена мин" name="MinPrice" value="@Model.NomFilter.MinPrice">
                </div>
                <div class="col-sm-12 col-lg-auto text-center px-1">
                    <label class="col-form-label">&mdash;</label>
                </div>
                <div class="col-sm-12 col-lg ml-auto pl-lg-0">
                    <input type="text" class="form-control light-control" placeholder="Цена макс" name="MaxPrice" value="@Model.NomFilter.MaxPrice">
                </div>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-12 col-lg-3 mb-2">
            <div class="border bg-main-light rounded-1 p-4">
                <label class="main-font h4 mt-2 mb-3 font-weight-bold">Цвет:</label>
                @foreach (var item in Model.SearchLookups.Colors.Take(5)) {
                    <label class="container-checkbox">
                        <span class="checkmark-label">@item.Value</span>
                        <input type="checkbox" name="Colors" value="@item.Key" @Html.AddValue(Model.NomFilter.Colors.Contains(item.Key), "checked")>
                        <span class="checkmark"></span>
                    </label>
                }
                <div class="collapse" id="colorsCollapse">
                    @foreach (var item in Model.SearchLookups.Colors.Skip(5))
                    {
                    <label class="container-checkbox">
                        <span class="checkmark-label">@item.Value</span>
                        <input type="checkbox" name="Colors" value="@item.Key" @Html.AddValue(Model.NomFilter.Colors.Contains(item.Key), "checked")>
                        <span class="checkmark"></span>
                    </label>
                    }
                </div>
                <button type="button" class="btn btn-basic btn-basic-sm btn-main-white-colored w-100 mt-3" data-toggle="collapse" data-target="#colorsCollapse">Показать остальное</button>
            </div>
        </div>
        <div class="col-sm-12 col-lg-3 mb-2">
            <div class="border bg-main-light rounded-1 p-4">
                <label class="main-font h4 mt-2 mb-3 font-weight-bold">Категории:</label>
                @foreach (var item in Model.SearchLookups.Categories.Take(5)) {
                    <label class="container-checkbox">
                        <span class="checkmark-label">@item.Name</span>
                        <input type="checkbox" name="Categories" value="@item.CategoryId1C" @Html.AddValue(Model.NomFilter.Categories.Contains((int) item.CategoryId1C), "checked")>
                        <span class="checkmark"></span>
                    </label>
                }
                <div class="collapse" id="categoriesCollapse">
                    @foreach (var item in Model.SearchLookups.Categories.Skip(5)) {
                    <label class="container-checkbox">
                        <span class="checkmark-label">@item.Name</span>
                        <input type="checkbox" name="Categories" value="@item.CategoryId1C" @Html.AddValue(Model.NomFilter.Categories.Contains((int)item.CategoryId1C), "checked")>
                        <span class="checkmark"></span>
                    </label>
                    }
                </div>
                <button type="button" class="btn btn-basic btn-basic-sm btn-main-white-colored w-100 mt-3" data-toggle="collapse" data-target="#categoriesCollapse">Показать остальное</button>
            </div>
        </div>
        <div class="col-sm-12 col-lg-3 mb-2">
            <div class="border bg-main-light rounded-1 p-4">
                <label class="main-font h4 mt-2 mb-3 font-weight-bold">Размер:</label>
                @foreach (var item in Model.SearchLookups.Sizes.Take(5)) {
                    <label class="container-checkbox">
                        <span class="checkmark-label">@item</span>
                        <input type="checkbox" name="Sizes" value="@item" @Html.AddValue(Model.NomFilter.Sizes.Contains(item), "checked")>
                        <span class="checkmark"></span>
                    </label>
                }
                <div class="collapse" id="sizesCollapse">
                    @foreach (var item in Model.SearchLookups.Sizes.Skip(5)) {
                    <label class="container-checkbox">
                        <span class="checkmark-label">@item</span>
                        <input type="checkbox" name="Sizes" value="@item" @Html.AddValue(Model.NomFilter.Sizes.Contains(item), "checked")>
                        <span class="checkmark"></span>
                    </label>
                    }
                </div>
                <button type="button" class="btn btn-basic btn-basic-sm btn-main-white-colored w-100 mt-3" data-toggle="collapse" data-target="#sizesCollapse">Показать остальное</button>
            </div>
        </div>
        <div class="col-sm-12 col-lg-3 mb-2">
            <div class="border bg-main-light rounded-1 p-4">
                <label class="main-font h4 mt-2 mb-3 font-weight-bold">Размерный ряд:</label>
                @foreach (var item in Model.SearchLookups.SizeLines.Take(5)) {
                    <label class="container-checkbox">
                        <span class="checkmark-label">@item</span>
                        <input type="checkbox" name="SizeLines" value="@item" @Html.AddValue(Model.NomFilter.SizeLines.Contains(item), "checked")>
                        <span class="checkmark"></span>
                    </label>
                }
                <div class="collapse" id="sizeLinesCollapse">
                    @foreach (var item in Model.SearchLookups.SizeLines.Skip(5))
                    {
                        <label class="container-checkbox">
                            <span class="checkmark-label">@item</span>
                            <input type="checkbox" name="SizeLines" value="@item" @Html.AddValue(Model.NomFilter.SizeLines.Contains(item), "checked")>
                            <span class="checkmark"></span>
                        </label>
                    }
                </div>
                <button type="button" class="btn btn-basic btn-basic-sm btn-main-white-colored w-100 mt-3" data-toggle="collapse" data-target="#sizeLinesCollapse">Показать остальное</button>
            </div>
        </div>
    </div>
</form>