Module.Partners.WebUI/Partners/Controllers/DocumentsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using KristaShop.Common.Helpers;
using KristaShop.Common.Models;
using KristaShop.Common.Models.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.FeatureManagement.Mvc;
using Module.Common.Business.Interfaces;
using Module.Common.WebUI.Base;
using Module.Common.WebUI.Infrastructure;
using Module.Partners.Business.Interfaces;
using Serilog;
using SmartBreadcrumbs.Nodes;

namespace Module.Partners.WebUI.Partners.Controllers {
    [FeatureGate(GlobalConstant.FeatureFlags.FeaturePartners)]
    [Authorize(AuthenticationSchemes = GlobalConstant.Session.FrontendScheme)]
    [Permission(ForPartnersOnly = true)]
    [Area(GlobalConstant.PartnersArea)]
    public class DocumentsController : AppControllerBase {
        private readonly IPartnerDocumentsService _documentsService;
        private readonly ILookupsService _lookupsService;
        private readonly ILogger _logger;

        public DocumentsController(IPartnerDocumentsService documentsService, ILookupsService lookupsService, ILogger logger) {
            _documentsService = documentsService;
            _lookupsService = lookupsService;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index() {
            return await Index(new DocumentsFilter());
        }
        
        [HttpPost]
        public async Task<IActionResult> Index(DocumentsFilter filter) {
            try {
                var result = await _documentsService.GetStorehouseDocumentsAsync(UserSession.UserId, filter);

                filter.DocumentTypesSelect = new SelectList(_documentsService.GetStorehouseDocumentsLookup(), "Key", "Value");
                filter.SizesSelect = new SelectList(await _lookupsService.GetSizesListAsync());

                SetBreadcrumbs("Order", "Index", "Личный кабинет", null, new MvcBreadcrumbNode(ActionName, ControllerName, "Мой магазин", areaName: ""));
                return View((result, filter));
            } catch (Exception ex) {
                _logger.Error(ex, "Failed to load partner reports index. {message}", ex.Message);
                return RedirectToAction("Common500", "Error");
            }
        }
        
        [HttpGet]
        public async Task<IActionResult> IncomeDocuments() {
            return await IncomeDocuments(new DocumentsFilter());
        }
        
        [HttpPost]
        public async Task<IActionResult> IncomeDocuments(DocumentsFilter filter) {
            try {
                filter.DocumentTypesSelect = new SelectList(_documentsService.GetStorehouseDocumentsLookup(), "Key", "Value");
                filter.SizesSelect = new SelectList(await _lookupsService.GetSizesListAsync());
                SetBreadcrumbs("Order", "Index", "Личный кабинет", null, new MvcBreadcrumbNode(ActionName, ControllerName, "Мой магазин", areaName: ""));
                return View(nameof(Index), (await _documentsService.GetIncomeDocumentsAsync(UserSession.UserId, filter), filter));
            } catch (Exception ex) {
                _logger.Error(ex, "Failed to load partner reports index. {message}", ex.Message);
                return RedirectToAction("Common500", "Error");
            }
        }
        
        [HttpGet]
        public async Task<IActionResult> SellingDocuments() {
            return await SellingDocuments(new DocumentsFilter());
        }
        
        [HttpPost]
        public async Task<IActionResult> SellingDocuments(DocumentsFilter filter) {
            try {
                filter.DocumentTypesSelect = new SelectList(_documentsService.GetStorehouseDocumentsLookup(), "Key", "Value");
                filter.SizesSelect = new SelectList(await _lookupsService.GetSizesListAsync());
                SetBreadcrumbs("Order", "Index", "Личный кабинет", null, new MvcBreadcrumbNode(ActionName, ControllerName, "Мой магазин", areaName: ""));
                return View(nameof(Index), (await _documentsService.GetSellingDocumentsAsync(UserSession.UserId, filter), filter));
            } catch (Exception ex) {
                _logger.Error(ex, "Failed to load partner reports index. {message}", ex.Message);
                return RedirectToAction("Common500", "Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> RevisionDocuments() {
            return await RevisionDocuments(new DocumentsFilter());
        }
        
        public async Task<IActionResult> RevisionDocuments(DocumentsFilter filter) {
            try {
                filter.DocumentTypesSelect = new SelectList(_documentsService.GetStorehouseDocumentsLookup(), "Key", "Value");
                filter.SizesSelect = new SelectList(await _lookupsService.GetSizesListAsync());
                SetBreadcrumbs("Order", "Index", "Личный кабинет", null, new MvcBreadcrumbNode(ActionName, ControllerName, "Мой магазин", areaName: ""));
                return View(nameof(Index), (await _documentsService.GetRevisionDocumentsAsync(UserSession.UserId, filter), filter));
            } catch (Exception ex) {
                _logger.Error(ex, "Failed to load partner reports index. {message}", ex.Message);
                return RedirectToAction("Common500", "Error");
            }
        }

        [Route("[area]/[controller]/[action]/{number:long}")]
        public async Task<IActionResult> Document(ulong number, bool grouped) {
            try {
                SetBreadcrumbs("Order", "Index", "Личный кабинет", null, new MvcBreadcrumbNode(ActionName, ControllerName, "Мой магазин", areaName: ""));
                if (!grouped) {
                    var model = await _documentsService.GetDocumentAsync(number, UserSession.UserId);
                    return View(model);
                } else {
                    var model = await _documentsService.GetDocumentWithGroupedItemsAsync(number, UserSession.UserId);
                    ViewBag.Sizes = new SelectList(model.Items
                        .SelectMany(x => x.SizesInfo.TotalAmountBySize.Where(c => c.Value > 0).Select(c => c.Key))
                        .Concat(model.Items.Select(x => x.ModelInfo.Size.Line))
                        .Distinct()
                        .OrderBy(x => x, new SizeStringComparer()));
                    
                    return View("DocumentGrouped", model);
                }
            } catch (Exception ex) {
                _logger.Error(ex, "Failed to get document. {message}", ex.Message);
                return RedirectToAction("Common500", "Error");
            }
        }
    }
}

Module.Partners.WebUI/Partners/Views/Documents/Document.cshtml
@model DocumentDTO<DocumentItemDetailedDTO>
@{
    Layout = "_PartnersLayout";
    ViewData["Title"] = $"Магазин | Документ {Model.Name}";
}

<div>
    <div class="d-flex my-2 flex-wrap d-block bg-main-info-light rounded-2 align-items-center @Html.AddValue(Model is RevisionDocumentDTO<DocumentItemDetailedDTO>, "py-1 px-3", "p-3")" data-toggle="collapse" href="#collapseStorehouseItems">
        <div class="font-weight-bold">
            <span>@Model.Descriptor</span>
            <span class="mx-1">@Model.Totals.ToString()</span>
        </div>
        <div class="ml-auto">
            @if (Model is RevisionDocumentDTO<DocumentItemDetailedDTO> revisionDocument) {
                var deficiencyDocument = @revisionDocument.GetDeficiencyDocument();
                <a asp-area="Partners"
                   asp-controller="Documents"
                   asp-action="Document"
                   asp-route-number="@deficiencyDocument.Number"
                   onclick="stopPropagation(event)"
                   class="btn btn-basic btn-success btn-shop mx-1">
                    Недостача по ревизии @deficiencyDocument.Totals.TotalAmount ед
                </a>
            }
            <span class="iconify icon-font-18px align-text-bottom" data-inline="false" data-icon="eva:expand-fill"></span>
        </div>
    </div>
    <div class="collapse show mb-4" id="collapseStorehouseItems">
        <table class="table table-striped table-bordered text-break border dataTable w-100 documentItemsTable">
            <thead>
            <tr>
                <th>Информация о модели</th>
                <th>Цвета</th>
                <th>Размер</th>
                <th>Кол-во</th>
                <th>На сумму</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="5">
                    <div class="d-flex flex-wrap d-block bg-main-info-light rounded-2 align-items-center p-3">
                        <div class="font-weight-bold">
                            <span>Итого:</span>
                            <span class="mx-1">@Model.Totals.ToString()</span>
                        </div>
                    </div>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var dataModel = @Html.AsJsObject(Model.Items);
    </script>
    <script src="/partners/js/documents/document.js" asp-append-version="true"></script>
}

Module.Partners.WebUI/Partners/Views/Documents/DocumentGrouped.cshtml
@model DocumentDTO<ModelGroupedDTO>
@{
    Layout = "_PartnersLayout";
    ViewData["Title"] = $"Магазин | Документ {Model.Name}";
}

<div>
    <partial name="_BasicFilter"/>
    <div class="d-flex my-2 flex-wrap d-block bg-main-info-light rounded-2 align-items-center @Html.AddValue(Model is RevisionDocumentDTO<ModelGroupedDTO>, "py-1 px-3", "p-3")" data-toggle="collapse" href="#collapseStorehouseItems">
        <div class="font-weight-bold">
            <span>@Model.Descriptor</span>
            <span class="mx-1">@Model.Totals.ToString()</span>
        </div>
        <div class="ml-auto">
            @if (Model is RevisionDocumentDTO<ModelGroupedDTO> revisionDocument) {
                var deficiencyDocument = @revisionDocument.GetDeficiencyDocument();
                <a asp-area="Partners"
                   asp-controller="Documents"
                   asp-action="Document"
                   asp-route-number="@deficiencyDocument.Number"
                   onclick="stopPropagation(event)"
                   class="btn btn-basic btn-success btn-shop mx-1">
                    Недостача по ревизии @deficiencyDocument.Totals.TotalAmount ед
                </a>
            }
            <span class="iconify icon-font-18px align-text-bottom" data-inline="false" data-icon="eva:expand-fill"></span>
        </div>
    </div>
    <div class="collapse show mb-4" id="collapseStorehouseItems">
        <table class="table table-striped table-bordered text-break border dataTable w-100 documentItemsTable">
            <thead>
            <tr>
                <th class="hide-arrows">
                    <div class="row mx-0 no-gutters">
                        <div class="col-3">
                            <span class="sorting" data-sort-target-col="modelKey">Информация о модели</span>
                        </div>
                        <div class="col-9">
                            <div class="row mx-0 no-gutters">
                                <div class="col-2">Цвета</div>
                                <div class="col-2">Размер</div>
                                <div class="col-3">
                                    <span class="sorting" data-sort-target-col="totalAmount">Кол-во</span>
                                </div>
                                <div class="col-2">
                                    <span class="sorting" data-sort-target-col="totalSum">На сумму</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </th>
                <th>Кол-во</th>
                <th>На сумму</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="3">
                    <div class="d-flex flex-wrap d-block bg-main-info-light rounded-2 align-items-center p-3">
                        <div class="font-weight-bold">
                            <span>Итого:</span>
                            <span class="mx-1">@Model.Totals.ToString()</span>
                        </div>
                    </div>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var dataModel = @Html.AsJsObject(Model.Items);
    </script>
    <script src="/partners/js/table-render-helper.js" asp-append-version="true"></script>
    <script src="/partners/js/documents/document-grouped.js" asp-append-version="true"></script>
}

Module.Partners.WebUI/Partners/Views/Documents/Index.cshtml
@using Microsoft.AspNetCore.Routing
@model (List<DocumentMovementAmountsDTO> Documents, DocumentsFilter Filter)
@{
    Layout = "_PartnersLayout";
    ViewData["Title"] = "Магазин | Журнал движения по складу";
}

<div>
    <div class="container-fluid p-0 customSearchWrapper filter-form-bordered">
        <form asp-action="@Context.GetRouteData().GetAction()" asp-controller="Documents">
            <div class="form-row mb-0 pl-1 main-font h4">
                <div class="form-group col-12 col-md-4 pl-0 pr-2">
                    <label class="text-bold">Поиск по артикулу</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span class="iconify icon-font" data-inline="false" data-icon="bx:bx-search"></span>
                            </span>
                        </div>
                        <input type="text" asp-for="Filter.Articul" name="Articul" class="form-control has-append-group" placeholder="Поиск по артикулу">
                        <div class="input-group-append">
                            <button type="button" class="btn btn-clear-input" onclick="clearInputGroup(this)">
                                <span class="iconify" data-inline="false" data-icon="clarity:close-line"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="form-group col-12 col-md-4 px-2">
                    <label class="text-bold">Поиск по цвету</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span class="iconify icon-font" data-inline="false" data-icon="bx:bx-search"></span>
                            </span>
                        </div>
                        <input type="text" asp-for="Filter.ColorName" name="ColorName" class="form-control has-append-group" placeholder="Поиск по цвету">
                        <div class="input-group-append">
                            <button type="button" class="btn btn-clear-input" onclick="clearInputGroup(this)">
                                <span class="iconify" data-inline="false" data-icon="clarity:close-line"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="form-group col-12 col-md-4 px-2">
                    <div class="d-flex">
                        <label class="text-bold">Поиск по размеру</label>
                        <div class="ml-auto">
                            <a asp-action="@Context.GetRouteData().GetAction()" class="link-base link-danger link-decoration-none" title="Сбросить фильтры">
                                <span class="iconify font-size-18 font-weight-6" data-inline="false" data-icon="grommet-icons:power-reset"></span>
                                <span class="font-weight-6 align-middle">Сброс</span>
                            </a>
                        </div>
                    </div>
                    <select asp-items="Model.Filter.SizesSelect" asp-for="Filter.Sizes" name="Sizes" class="selectpicker form-control form-control-sm show-menu-arrow" data-dropup-auto="false" data-size="10" data-live-search="true" data-actions-box="true" multiple data-title="Укажите размер">
                    </select>
                </div>
            </div>
            <div class="form-row pl-1 main-font h4">
                <div class="form-group col-12 col-md-4 pl-0 pr-2">
                    <label class="text-bold">Период от и до:</label>
                    <div class="form-row mx-0">
                        <div class="col pl-0 pr-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <span class="iconify icon-font" data-inline="false" data-icon="bx:bx-search"></span>
                                    </span>
                                </div>
                                <input asp-for="Filter.DateFrom" name="DateFrom" class="form-control flatpickr flatpickr-input has-append-group" type="text" value="@(Model.Filter.DateFrom.ToBasicString())" placeholder="От" data-datetime-picker>
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-clear-input" onclick="clearInputGroup(this)">
                                        <span class="iconify" data-inline="false" data-icon="clarity:close-line"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col px-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <span class="iconify icon-font" data-inline="false" data-icon="bx:bx-search"></span>
                                    </span>
                                </div>
                                <input asp-for="Filter.DateTo" name="DateTo" class="form-control flatpickr flatpickr-input has-append-group" type="text" value="@(Model.Filter.DateTo.ToBasicString())" placeholder="До" data-datetime-picker>
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-clear-input" onclick="clearInputGroup(this)">
                                        <span class="iconify" data-inline="false" data-icon="clarity:close-line"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-12 col-md-4 px-2">
                    <label class="text-bold">По виду документа</label>
                    <select asp-items="Model.Filter.DocumentTypesSelect" asp-for="Filter.DocumentTypes" name="DocumentTypes" class="selectpicker form-control form-control-sm show-menu-arrow" data-dropup-auto="false" data-size="10" data-live-search="true" data-actions-box="true" data-title="Выберите тип документа">
                    </select>
                </div>
                <div class="form-group col-12 col-md-4 px-2">
                    <div class="d-flex flex-row justify-content-end align-items-end">
                        <button type="submit" class="btn btn-basic btn-success mt-4">Поиск</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    @if (Model.Documents.Any()) {
        <div class="d-flex my-2 flex-wrap d-block bg-main-info-light rounded-2 align-items-center p-3" data-toggle="collapse" href="#collapseStorehouseItems">
            <div class="font-weight-bold">
                <span>Документы по движению на складе за период</span>
                <span class="mx-1">@Model.Filter.DateFrom.ToBasicString()</span>
                <span>по</span>
                <span class="mx-1">@Model.Filter.DateTo.ToBasicString()</span>
            </div>
            <div class="ml-auto">
                <span class="iconify icon-font-18px align-text-bottom" data-inline="false" data-icon="eva:expand-fill"></span>
            </div>
        </div>
        <div class="collapse show mb-4" id="collapseStorehouseItems">
            <table class="table table-striped table-bordered text-break border dataTable w-100 documentsTable">
                <thead>
                <tr>
                    <th>Дата</th>
                    <th>Номер</th>
                    <th>Документ</th>
                    <th>Приход</th>
                    <th>Расход</th>
                    <th></th>
                </tr>
                </thead>
                <tfoot>
                <tr class="font-weight-bold">
                    <td>Итого</td>
                    <td colspan="2"></td>
                    <td>
                        <span id="totalIncomeAmount"></span>
                    </td>
                    <td>
                        <span id="totalWriteOffAmount"></span>
                    </td>
                    <th></th>
                </tr>
                </tfoot>
            </table>
        </div>
    } else {
        <div class="row text-center justify-content-center main-font h1 pt-5">По вашему запросу не найдено документов</div>
    }
</div>


@section Scripts {
    <script type="text/javascript">
        var dataModel = @Html.AsJsObject(Model.Documents);
    </script>
    <script src="/partners/js/documents/storehouse-documents.js" asp-append-version="true"></script>
}