Module.App.WebUI/Controllers/FeedbackController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using AutoMapper;
using GoogleReCaptcha.V3.Interface;
using KristaShop.Common.Enums;
using KristaShop.Common.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Module.App.Business.Interfaces;
using Module.App.Business.Models;
using Module.App.WebUI.Models;
using Module.Common.WebUI.Base;
using Module.Common.WebUI.Extensions;
using Module.Common.WebUI.Infrastructure;
using Serilog;

namespace Module.App.WebUI.Controllers {
    [Permission]
    [Authorize(AuthenticationSchemes = GlobalConstant.Session.AllFrontSchemes)]
    public class FeedbackController : AppControllerBase {
        private readonly IFeedbackService _feedbackService;
        private readonly IMapper _mapper;
        private readonly ILogger _logger;
        private readonly ICaptchaValidator _captchaValidator;
        private readonly GlobalSettings _globalSettings;

        public FeedbackController(IFeedbackService feedbackService, IMapper mapper, ILogger logger,
            IOptions<GlobalSettings> _globalSettingsOptions, ICaptchaValidator captchaValidator) {
            _feedbackService = feedbackService;
            _mapper = mapper;
            _logger = logger;
            _captchaValidator = captchaValidator;
            _globalSettings = _globalSettingsOptions.Value;
        }

        [AllowAnonymous]
        public IActionResult Get() {
            var model = UserSession?.User != null ? _mapper.Map<FeedbackViewModel>(UserSession.User) : new FeedbackViewModel();
            return PartialView("_FeedbackFormPartial", model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FeedbackViewModel model) {
            if (ModelState.IsValid) {
                if (await _captchaValidator.IsCaptchaPassedAsync(model.Captcha)) {
                    try {
                        var feedbackModel = _mapper.Map<FeedbackDTO>(model);
                        feedbackModel.Type = FeedbackType.Basic;
                        var result = await _feedbackService.InsertFeedback(feedbackModel);

                        if (!result.IsSuccess) {
                            ModelState.TryAddModelErrors(result.Messages);
                        }
                    } catch (Exception ex) {
                        _logger.Error(ex, "Failed to create feedback. {message}", ex.Message);
                        ModelState.TryAddModelErrors(OperationResult.Failure().Messages);
                    }
                } else {
                    ModelState.AddModelError(string.Empty, "Капча не валидна");
                }
            }

            return PartialView("_FeedbackFormPartial", model);
        }

        public IActionResult GetWithFile() {
            var model = new AuthFeedbackViewModel();
            return PartialView("_FeedbackCoplaintsPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWithFile(AuthFeedbackViewModel model) {
            if (ModelState.IsValid) {
                try {
                    var feedbackModel = _mapper.Map<FeedbackDTO>(UserSession.User);
                    _mapper.Map(model, feedbackModel);
                    feedbackModel.Type = FeedbackType.ComplaintsAndSuggestions;

                    OperationResult result;
                    if (model.File != null) {
                        var file = await _getFeedbackFileDto(model);
                        result = await _feedbackService.InsertFeedbackWithFileAsync(feedbackModel, file);
                    } else {
                        result = await _feedbackService.InsertFeedback(feedbackModel);
                    }

                    if (!result.IsSuccess) {
                        ModelState.TryAddModelErrors(result.Messages);
                    }
                } catch (Exception ex) {
                    _logger.Error(ex, "Failed to create feedback. {message}", ex.Message);
                    ModelState.TryAddModelErrors(OperationResult.Failure().Messages);
                }
            }

            return PartialView("_FeedbackCoplaintsPartial", model);
        }

        private async Task<FeedbackCreateFileDTO> _getFeedbackFileDto(AuthFeedbackViewModel model) {
            var file = new FeedbackCreateFileDTO {
                OriginalName = model.File.FileName,
                FileStream = new MemoryStream(),
                FilesDirectoryPath = _globalSettings.FilesDirectoryPath,
                Directory = _globalSettings.FeedbackFilesDirectory
            };
            await model.File.CopyToAsync(file.FileStream);
            return file;
        }

        public IActionResult GetManagementContacts() {
            return PartialView("_FeedbackManagementContactsPartial", new ManagementContactsFeedbackViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateManagementContacts(ManagementContactsFeedbackViewModel model) {
            if (ModelState.IsValid) {
                try {
                    var feedbackModel = _mapper.Map<FeedbackDTO>(UserSession.User);
                    _mapper.Map(model, feedbackModel);
                    feedbackModel.Type = FeedbackType.ManagementContacts;
                    var result = await _feedbackService.InsertFeedback(feedbackModel);

                    if (!result.IsSuccess) {
                        ModelState.TryAddModelErrors(result.Messages);
                    }
                } catch (Exception ex) {
                    _logger.Error(ex, "Failed to create feedback. {message}", ex.Message);
                    ModelState.TryAddModelErrors(OperationResult.Failure().Messages);
                }
            }

            return PartialView("_FeedbackManagementContactsPartial", model);
        }
    }
}

Module.App.WebUI/Views/Shared/_FeedbackPartial.cshtml
@using KristaShop.Common.Extensions
<div class="modal fade rounded-3" id="feedbackModal" tabindex="-1" role="dialog" aria-labelledby="feedbackModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <ul class="nav nav-justified" id="feedbackTab" role="tablist">
                    @if (Context.User.Identity.IsAuthenticated && !Context.User.IsGuest()) {
                        <li class="nav-item">
                            <a class="nav-link link-base link-dark active header-font h3 text-uppercase m-auto" id="feedback-complaints-tab" data-toggle="tab" href="#feedback-complaints" role="tab" aria-controls="feedback" aria-selected="true" data-url="@Url.Action("GetWithFile", "Feedback")" data-callback="feedbackSendCallback">Книга жалоб и предложений</a>
                        </li>
                    } else {
                        <li class="nav-item">
                            <a class="nav-link link-base link-dark active header-font h3 text-uppercase m-auto" id="feedback-tab" data-toggle="tab" href="#feedback" role="tab" aria-controls="feedback" aria-selected="true" data-url="@Url.Action("Get", "Feedback")" data-callback="feedbackSendCallback">Обратная связь</a>
                        </li>
                    }
                </ul>
                <div class="tab-content mt-4" id="feedbackTabContent">
                    @if (Context.User.Identity.IsAuthenticated && !Context.User.IsGuest()) {
                        <div class="tab-pane fade show active" id="feedback-complaints" role="tabpanel" aria-labelledby="feedback-complaints-tab">

                        </div>
                    } else {
                        <div class="tab-pane fade show active" id="feedback" role="tabpanel" aria-labelledby="feedback-tab">

                        </div>
                    }
                </div>
            </div>
            <div class="collapse" id="authenticatedFeedbackModalCollapse">
                <div class="modal-footer text-center text-white bg-active m-auto p-3">
                </div>
            </div>
        </div>
    </div>
</div>
@if (Context.User.Identity.IsAuthenticated && !Context.User.IsGuest()) {
    <div class="modal fade" id="feedbackContactsModal" tabindex="-1" role="dialog" aria-labelledby="feedbackContactsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <ul class="nav nav-justified" id="feedbackContactsTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link link-base link-dark active header-font h3 text-uppercase m-auto" id="feedback-management-contacts-tab" data-toggle="tab" href="#feedback-management-contacts" role="tab" aria-controls="feedback" aria-selected="true" data-url="@Url.Action("GetManagementContacts", "Feedback")" data-callback="feedbackSendCallback">Связь с руководством</a>
                        </li>
                    </ul>
                    <div class="tab-content mt-5" id="feedbackContactsTabContent">
                        <div class="tab-pane fade show active" id="feedback-management-contacts" role="tabpanel" aria-labelledby="feedback-management-contacts-tab">
                        </div>
                    </div>
                </div>
                <div class="collapse" id="feedbackModalCollapse">
                    <div class="modal-footer text-center text-white bg-active m-auto p-3">
                    </div>
                </div>
            </div>
        </div>
    </div>
}